.gitignore, Dockerfile, app/models.py, app/templates/index.html, db/my.cnf, docker-compose.yml, koko/settings.py, nginx/app.conf, requirements.txt
docker部署
包括django应用、mysql数据库和nginx应用部署
mysql需要建立test数据库（   ）
=> docker compose_up

app/views.py, koko/urls.py, mine/final.py
增加了后端接受读音的功能与路由
目前测试是使用的mine目录下的hi.m4a文件作为输入，最后返回输出
暂时没有对用户合法性的判定
已经经过本机验证，由于服务器安装贼jb慢还没有测
=> accent_read

app/models.py, app/views.py
调整了数据库的结构
将原先每个用户拥有一个朗读记录表改为所有用户的朗读记录全部存放于一张表中
其他表的更改也是如此
=> fix-models

app/views.py
=> 朗读记录更新基本完成

app/models.py, app/views.py
在detail函数中增加了添加数据到数据库的操作
将数据库储存格式修改
=> Detail data

app/models.py, app/views.py, koko/urls.py
=> login_info1

app/views.py, koko/urls.py
实现了首选项的部分路由，包括更改昵称、记录保存时间以及是否保存朗读语音
没有对传入参数的正确性进行检查
具体格式请参见API接口文档
=> setting_url

app/models.py, app/views.py, koko/urls.py
=> setting_headicon

app/views.py, koko/urls.py
=> wordbook_remove

app/models.py, app/views.py, koko/urls.py
实现了单词添加到单词本与删除的功能
修改了数据库中单词关联的存储方式
=> word_add_remove

koko/urls.py
=> bugfix_urls_fixed

app/models.py, app/views.py
数据库加入用户uid与关注者，在fanhuiglobalData时增加了两者的返回。
review目的：看看还有没有需要增加的用户信息
=> feature_models_user_info_untested

app/views.py, koko/urls.py
实现了uidsearch功能，还未进行完全测试，使用两个不同uid用户进行相互搜索时能够在前端得到正确的结果
=> Feature friend uidsearch

app/views.py, koko/urls.py
实现了好友列表返回的功能。
返回格式中只有前三个参数，第四个参数尚不明确（0？）
只进行了两个用例用户之间的测试，由于用户添加功能还没实现，是在数据库中直接对好友信息进行的更改之后观察的结果
没有进行实际测试
=> Feature friend list

app/models.py, app/views.py, dicts/dic_func.py
由于提前写了，部分需求功能在该函数实现之前没有得到实现，现在将其合并到分支。
=> feature_friend_follow主分支同步

app/models.py, app/views.py, koko/urls.py
实现了添加好友的功能
通过postman对两个用例用户之间进行了测试
没有实际测试
=> Feature friend follow

app/views.py, koko/urls.py
实现了取消关注的功能，没有参数审查
通过postman进行了两个用例用户之间的测试
没有实际测试
=> feature_friends_unfollow_untested

app/views.py
=> bugfix_friends_uidsearch

app/views.py, koko/urls.py
=> feature_friends_headicon_untested

app/views.py, koko/urls.py
=> feature_friends_namesearch_untested

app/views.py, koko/urls.py
修复bug:
headicon：如果不是关注者现在也可以正常返回头像
查询：增加了是否关注的选项
=> feature_friends_namesearch_bugfix+

app/views.py, koko/urls.py
=> feature_friends_info_untested

app/models.py
=> Feature models flwbs

app/models.py, app/views.py, koko/urls.py
实现了单词本的订阅功能
已经通过postman与增加的测试路由进行了测试
尚有细节未完善，包括但不限于订阅的限制以及访问
=> feature_friends_subscribe_untested

app/views.py, koko/urls.py
=> feature_friends_unsubscribe_untested

app/models.py, app/views.py, koko/urls.py
=> feature_wb_type_untested

app/views.py
实现了登陆时返回数据的修改
包括增加了返回的订阅单词本的信息
=> bugfix_login_untested

app/views.py
修改了friends_info中返回值，增加了uid和单词本的信息
=> bugfix_friends_info

app/views.py
=> bugfix_login_fixed

app/views.py
=> bugfix_models_user_info_fixed

app/views.py
修复了单词本封面的路由
单词本封面图片不能太大（不超过500kb）
=> Bugfix wb image set

app/views.py, koko/urls.py
=> Feature friends wbcover

app/views.py
在login的返回数据中增加了订阅单词本的following属性
修正了在搜索界面能够搜索到自己的问题
=> bugfix_login+_fixed

app/views.py
=> feature_paramcheck

app/views.py
将截至rewrite_paramcheck所作的修改同步到test_user进行测试
=> test_user分支同步

app/func/friends.py, app/func/login.py, app/func/read.py, app/func/setting.py, app/func/wb.py, app/func/word.py, app/mywrapper.py, app/views.py, koko/urls.py
实现了装饰器进行参数校验
将views.py中函数内容进行分离
=> Rewrite_function
